### PR TITLE
Bug fix for GPD WIN MAX screen

### PR DESCRIPTION
**Pull request by a342191555**
Thank you so much for these scripts, however, there're few little bugs for working for GPD WIN MAX.
I've fixed some. And now it works well on GPD WIN MAX.
Tested on elementaryOS 5.1.6 (Built on Ubuntu 18.04.4 LTS)

### CODE REVIEW

**Comment by flexiondotorg** [comment]
@a342191555 Can you explain what you changed in the EDID file. In this commit (https://github.com/wimpysworld/umpc-ubuntu/commit/78f35bd222be7a4c7308f31daee3cb82abc96d44) I explained how I originally created it. It would be good to have a record of your improvements :slightly_smiling_face:

**Comment by a342191555** [comment]
I havn't tried to create the EDID file by my own following [this instruction](https://github.com/cychai1995/gpd-win-max-wayland-ubuntu/blob/master/README.md).However, I found the EDID file in your previous commit  (78f35bd)does not work. 

But when I turn to the post which the author mentioned in 2020/09/01 update, there's another EDID file which works well for me. So I changed the commit's file, which is exactly same as the one [here](https://www.reddit.com/r/gpdwin/comments/ik3dje/gpd_win_max_display_fix_in_linux/).😊

**Comment by flexiondotorg** [comment]
I have a GPD WIN Max now @a342191555. I've got the remaining kinks (monitor rotation, touchscreen orientation) worked out. With those changes in place, using my original EDID and the one you submit, both work them same :man_shrugging:  I'll update this repo a bit later :slightly_smiling_face:

**Comment by a342191555** [comment]
That seems strange.

This time I use the EDID with your existing commit, the screen works well.
But I'm pretty sure when I used for the newly installed system (elementaryOS 5.1.6 , with no other firmware/kernel updates), it didn't work.

Don't know where goes wrong. 😣

**Comment by flexiondotorg** [comment]
Merged via https://github.com/wimpysworld/umpc-ubuntu/commit/4fb5c52b9042505bf235aa9d9fe52319d2f02455

**Pull request closed without merging**
